sendjob_text = ['#!/bin/bash\n',
'#PBS -N un_sub_l\n',
'#PBS -q medium\n',
'#PBS -l select=1:ncpus=1:mem=1024mb\n',
'#PBS -j eo\n',
'echo `hostname`\n',
'cd $PBS_O_WORKDIR\n',
'MYCOMMAND=',
'\n$MYCOMMAND\n',
'cd -\n']
